// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.24.0
//
// updated_at: 2025-03-24 20:22:07
// source: pro/Project.proto
// 
package project

import (
	"github.com/goal-web/contracts"
	project "github.com/goal-web/goal/app/requests/project"
	"github.com/goal-web/goal/app/response"
	svc "github.com/goal-web/goal/app/services/project"
	"github.com/goal-web/validation"
)

func ProjectServiceRouter(router contracts.HttpRouter) {
	routeGroup := router.Group("/project")
	routeGroup.Post("/CreateProject", ProjectServiceCreateProject)
	routeGroup.Get("/GetProject", ProjectServiceGetProject)
	routeGroup.Get("/ListProjects", ProjectServiceListProjects)
	routeGroup.Post("/UpdateProject", ProjectServiceUpdateProject)
	routeGroup.Post("/DeleteProject", ProjectServiceDeleteProject)
}
func ProjectServiceCreateProject(request contracts.HttpRequest) any {
	var req project.CreateProjectReq

	if err := request.Parse(&req); err != nil {
		return response.ParseReqErr(err)
	}

	if err := validation.Struct(req); err != nil {
		return response.InvalidReq(err)
	}

	resp, err := svc.ProjectServiceCreateProject(&req, request)
	if err != nil {
		return response.BizErr(err)
	}

	return response.Success(resp)
}
func ProjectServiceGetProject(request contracts.HttpRequest) any {
	var req project.GetProjectReq

	if err := request.Parse(&req); err != nil {
		return response.ParseReqErr(err)
	}

	if err := validation.Struct(req); err != nil {
		return response.InvalidReq(err)
	}

	resp, err := svc.ProjectServiceGetProject(&req, request)
	if err != nil {
		return response.BizErr(err)
	}

	return response.Success(resp)
}
func ProjectServiceListProjects(request contracts.HttpRequest) any {
	var req project.ListProjectsReq

	if err := request.Parse(&req); err != nil {
		return response.ParseReqErr(err)
	}

	if err := validation.Struct(req); err != nil {
		return response.InvalidReq(err)
	}

	resp, err := svc.ProjectServiceListProjects(&req, request)
	if err != nil {
		return response.BizErr(err)
	}

	return response.Success(resp)
}
func ProjectServiceUpdateProject(request contracts.HttpRequest) any {
	var req project.UpdateProjectReq

	if err := request.Parse(&req); err != nil {
		return response.ParseReqErr(err)
	}

	if err := validation.Struct(req); err != nil {
		return response.InvalidReq(err)
	}

	resp, err := svc.ProjectServiceUpdateProject(&req, request)
	if err != nil {
		return response.BizErr(err)
	}

	return response.Success(resp)
}
func ProjectServiceDeleteProject(request contracts.HttpRequest) any {
	var req project.DeleteProjectReq

	if err := request.Parse(&req); err != nil {
		return response.ParseReqErr(err)
	}

	if err := validation.Struct(req); err != nil {
		return response.InvalidReq(err)
	}

	resp, err := svc.ProjectServiceDeleteProject(&req, request)
	if err != nil {
		return response.BizErr(err)
	}

	return response.Success(resp)
}
