// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.24.0
//
// updated_at: 2025-03-24 11:05:04
// source: pro/user.proto
// 
package user

import (
	"github.com/goal-web/contracts"
	user "github.com/goal-web/goal/app/requests/user"
	user0 "github.com/goal-web/goal/app/results/user"
)

var AuthServiceDefine AuthServiceStatic

type AuthServiceStatic struct {
	LoginByWxAppCode func(req *user.LoginByWxCodeReq, ctx contracts.Context) (*user0.LoginByWxResult, error)
	LoginByWxAppInfo func(req *user.LoginByWxInfoReq, ctx contracts.Context) (*user0.LoginByWxResult, error)
}

func AuthServiceLoginByWxAppCode(req *user.LoginByWxCodeReq, ctx contracts.Context) (*user0.LoginByWxResult, error) {
	if AuthServiceDefine.LoginByWxAppCode != nil {
		return AuthServiceDefine.LoginByWxAppCode(req, ctx)
	}
	return nil, nil
}

func AuthServiceLoginByWxAppInfo(req *user.LoginByWxInfoReq, ctx contracts.Context) (*user0.LoginByWxResult, error) {
	if AuthServiceDefine.LoginByWxAppInfo != nil {
		return AuthServiceDefine.LoginByWxAppInfo(req, ctx)
	}
	return nil, nil
}
