// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.24.0
//
// updated_at: 2025-03-24 20:21:38
// source: pro/Project.proto
// 
package project

import (
	models "github.com/goal-web/goal/app/models"
)

type GetProjectRessult struct {
	Project models.ProjectModel `json:"project" query:"project" form:"project"`
}
