// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.24.0
//
// updated_at: 2025-03-24 20:22:07
// source: pro/Project.proto
// 
package project

import (
	"github.com/goal-web/contracts"
	project "github.com/goal-web/goal/app/requests/project"
	project0 "github.com/goal-web/goal/app/results/project"
)

var ProjectServiceDefine ProjectServiceStatic

type ProjectServiceStatic struct {
	CreateProject func(req *project.CreateProjectReq, ctx contracts.Context) (*project0.CreateProjectResult, error)
	GetProject    func(req *project.GetProjectReq, ctx contracts.Context) (*project0.GetProjectResult, error)
	ListProjects  func(req *project.ListProjectsReq, ctx contracts.Context) (*project0.ListProjectsResult, error)
	UpdateProject func(req *project.UpdateProjectReq, ctx contracts.Context) (*project0.UpdateProjectResult, error)
	DeleteProject func(req *project.DeleteProjectReq, ctx contracts.Context) (*project0.DeleteProjectResult, error)
}

func ProjectServiceCreateProject(req *project.CreateProjectReq, ctx contracts.Context) (*project0.CreateProjectResult, error) {
	if ProjectServiceDefine.CreateProject != nil {
		return ProjectServiceDefine.CreateProject(req, ctx)
	}
	return nil, nil
}

func ProjectServiceGetProject(req *project.GetProjectReq, ctx contracts.Context) (*project0.GetProjectResult, error) {
	if ProjectServiceDefine.GetProject != nil {
		return ProjectServiceDefine.GetProject(req, ctx)
	}
	return nil, nil
}

func ProjectServiceListProjects(req *project.ListProjectsReq, ctx contracts.Context) (*project0.ListProjectsResult, error) {
	if ProjectServiceDefine.ListProjects != nil {
		return ProjectServiceDefine.ListProjects(req, ctx)
	}
	return nil, nil
}

func ProjectServiceUpdateProject(req *project.UpdateProjectReq, ctx contracts.Context) (*project0.UpdateProjectResult, error) {
	if ProjectServiceDefine.UpdateProject != nil {
		return ProjectServiceDefine.UpdateProject(req, ctx)
	}
	return nil, nil
}

func ProjectServiceDeleteProject(req *project.DeleteProjectReq, ctx contracts.Context) (*project0.DeleteProjectResult, error) {
	if ProjectServiceDefine.DeleteProject != nil {
		return ProjectServiceDefine.DeleteProject(req, ctx)
	}
	return nil, nil
}
