// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.24.0
//
// updated_at: 2025-03-24 20:22:07
// source: pro/user.proto
// 
package user

import (
	"github.com/goal-web/contracts"
)

type LoginByWxInfoReq struct {
	Iv            string `json:"iv" query:"iv" form:"iv"`
	SessionKey    string `json:"sessionKey" query:"sessionKey" form:"sessionKey"`
	EncryptedData string `json:"encryptedData" query:"encryptedData" form:"encryptedData"`
}

func (model *LoginByWxInfoReq) ToFields() contracts.Fields {
	if model == nil {
		return nil
	}
	fields := contracts.Fields{
		"iv":            model.Iv,
		"sessionKey":    model.SessionKey,
		"encryptedData": model.EncryptedData,
	}
	return fields
}
