// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.23.2
//
// updated_at: 2024-10-09 19:07:27
// source: pro/user.proto
// 
package user

import (
	"github.com/goal-web/contracts"
)

type LoginByWxCodeReq struct {
	Code string `json:"code"`
}

func (model *LoginByWxCodeReq) ToFields() contracts.Fields {
	if model == nil {
		return nil
	}
	fields := contracts.Fields{
		"code": model.Code,
	}
	return fields
}
