// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.23.2
//
// updated_at: 2024-10-09 02:33:34
// source: pro/user.proto
// 
package user

import ()

type WechatInfoData struct {
	City      string `json:"city"`
	Gender    int64  `json:"gender"`
	OpenId    string `json:"open_id"`
	Country   string `json:"country"`
	Language  string `json:"language"`
	Nickname  string `json:"nickname"`
	Province  string `json:"province"`
	AvatarUrl string `json:"avatar_url"`
}
