// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.24.0
//
// updated_at: 2025-03-24 11:05:04
// source: pro/user.proto
// 
package user

import ()

type WechatInfoData struct {
	City      string `json:"city" query:"city" form:"city"`
	Gender    int64  `json:"gender" query:"gender" form:"gender"`
	OpenId    string `json:"open_id" query:"open_id" form:"open_id"`
	Country   string `json:"country" query:"country" form:"country"`
	Language  string `json:"language" query:"language" form:"language"`
	Nickname  string `json:"nickname" query:"nickname" form:"nickname"`
	Province  string `json:"province" query:"province" form:"province"`
	AvatarUrl string `json:"avatar_url" query:"avatar_url" form:"avatar_url"`
}
