// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.24.0
//
// updated_at: 2025-03-22 23:44:41
// source: pro/Project.proto
// 
package models

import (
	"encoding/json"
	"fmt"
	"github.com/goal-web/collection"
	"github.com/goal-web/contracts"
	"github.com/goal-web/database/table"
	"github.com/goal-web/migration/migrate"
	"github.com/goal-web/supports/logs"
	"github.com/goal-web/supports/utils"
	"github.com/spf13/cast"
)

var (
	ProjectUserRelation contracts.RelationType = "user"
)

// ProjectModel
// @timestamps
type ProjectModel struct {
	Id uint64 `json:"id" query:"id" form:"id" db:"id;type:BIGINT UNSIGNED;not null;primary key;AUTO_INCREMENT;"`

	Uuid string `json:"uuid" query:"uuid" form:"uuid" db:"uuid;type:VARCHAR(255);not null;"`

	Name string `json:"name" query:"name" form:"name" db:"name;type:VARCHAR(255);not null;"`

	CreatorId int32 `json:"creator_id" query:"creator_id" form:"creator_id" db:"creator_id;type:INT;not null;"`

	GroupId int32 `json:"group_id" query:"group_id" form:"group_id" db:"group_id;type:INT;not null;"`

	KeyId int32 `json:"key_id" query:"key_id" form:"key_id" db:"key_id;type:INT;not null;"`

	RepoAddress string `json:"repo_address" query:"repo_address" form:"repo_address" db:"repo_address;type:VARCHAR(255);not null;"`

	ProjectPath string `json:"project_path" query:"project_path" form:"project_path" db:"project_path;type:VARCHAR(255);not null;"`

	DefaultBranch string `json:"default_branch" query:"default_branch" form:"default_branch" db:"default_branch;type:VARCHAR(255);not null;"`

	Settings string `json:"settings" query:"settings" form:"settings" db:"settings;type:VARCHAR(255);not null;"`

	CreatedAt string `json:"created_at" query:"created_at" form:"created_at" db:"created_at;type:timestamp;default CURRENT_TIMESTAMP;"`

	UpdatedAt string `json:"updated_at" query:"updated_at" form:"updated_at" db:"updated_at;type:timestamp;DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;"`

	_raw    contracts.Fields
	_update contracts.Fields
	_append contracts.Fields
	_hidden map[string]struct{}

	_relation_loaded map[contracts.RelationType]struct{}
	_User            *UserModel
}

var ProjectDefine ProjectStatic

type ProjectStatic struct {
	TableName           string
	Hidden              []string
	Indexes             []string
	With                []contracts.RelationType
	Appends             map[string]func(model *ProjectModel) any
	IdGetter            func(model *ProjectModel, raw uint64) uint64
	IdSetter            func(model *ProjectModel, raw uint64) uint64
	UuidGetter          func(model *ProjectModel, raw string) string
	UuidSetter          func(model *ProjectModel, raw string) string
	NameGetter          func(model *ProjectModel, raw string) string
	NameSetter          func(model *ProjectModel, raw string) string
	CreatorIdGetter     func(model *ProjectModel, raw int32) int32
	CreatorIdSetter     func(model *ProjectModel, raw int32) int32
	GroupIdGetter       func(model *ProjectModel, raw int32) int32
	GroupIdSetter       func(model *ProjectModel, raw int32) int32
	KeyIdGetter         func(model *ProjectModel, raw int32) int32
	KeyIdSetter         func(model *ProjectModel, raw int32) int32
	RepoAddressGetter   func(model *ProjectModel, raw string) string
	RepoAddressSetter   func(model *ProjectModel, raw string) string
	ProjectPathGetter   func(model *ProjectModel, raw string) string
	ProjectPathSetter   func(model *ProjectModel, raw string) string
	DefaultBranchGetter func(model *ProjectModel, raw string) string
	DefaultBranchSetter func(model *ProjectModel, raw string) string
	SettingsGetter      func(model *ProjectModel, raw string) string
	SettingsSetter      func(model *ProjectModel, raw string) string
	CreatedAtGetter     func(model *ProjectModel, raw string) string
	CreatedAtSetter     func(model *ProjectModel, raw string) string
	UpdatedAtGetter     func(model *ProjectModel, raw string) string
	UpdatedAtSetter     func(model *ProjectModel, raw string) string

	Saving           func(model *ProjectModel) contracts.Exception
	Saved            func(model *ProjectModel)
	Updating         func(model *ProjectModel, fields contracts.Fields) contracts.Exception
	Updated          func(model *ProjectModel, fields contracts.Fields)
	Deleting         func(model *ProjectModel) contracts.Exception
	Deleted          func(model *ProjectModel)
	PrimaryKeyGetter func(model *ProjectModel) any
}

func ProjectMigrator() migrate.Migrator {
	return func(executor contracts.SqlExecutor) contracts.Exception {
		return migrate.Migrate(ProjectDefine.TableName, ProjectDefine.Indexes, ProjectModel{}, executor)
	}
}

func init() {
	ProjectDefine.TableName = "projects"
	ProjectDefine.Appends = make(map[string]func(model *ProjectModel) any)
}

func NewProjectModel(fields contracts.Fields) *ProjectModel {
	var model = ProjectModel{
		_raw: fields,
	}
	model.Set(fields)
	return &model
}

func ProjectModelSingleRelationSetter[T any](key contracts.RelationType) func(item *ProjectModel, value []any) {
	return func(item *ProjectModel, values []any) {
		var value T
		if len(values) > 0 {
			value = values[0].(T)
		}
		item.Set(contracts.Fields{
			string(key): value,
		})
	}
}
func ProjectModelMultiRelationSetter[T any](key contracts.RelationType) func(item *ProjectModel, value []any) {
	return func(model *ProjectModel, value []any) {
		var results []T
		for _, item := range value {
			results = append(results, item.(T))
		}
		model.Set(contracts.Fields{string(key): results})
	}
}

func ProjectModelLocalKeyGetter(key string) func(item *ProjectModel) any {
	return func(item *ProjectModel) any {
		return item.Get(key)
	}
}

func ProjectModelRelationGetter[T any](query func() *table.Table[T], foreignKey string) func(keys []any) map[string][]any {
	return func(keys []any) map[string][]any {
		var results = map[string][]any{}
		for key, values := range query().WhereIn(foreignKey, keys).Get().GroupBy(foreignKey) {
			results[key] = collection.New(values).ToAnyArray()
		}
		return results
	}
}

func ProjectModelThroughRelationGetter[T any](query func() *table.Table[T], midTable, firstKey, secondKey, secondLocalKey string) func(keys []any) map[string][]any {
	return func(keys []any) map[string][]any {
		var results = map[string][]any{}
		groupKey := fmt.Sprintf("%s.%s", midTable, firstKey)
		for key, values := range query().
			AddSelect(fmt.Sprintf("(%s) as _group_key", groupKey)).
			WhereIn(groupKey, keys).
			Join(midTable, fmt.Sprintf("%s.%s", midTable, secondLocalKey), "=", fmt.Sprintf("%s.%s", query().GetTableName(), secondKey)).
			Get().GroupBy("_group_key") {
			results[key] = collection.New(values).ToAnyArray()
		}
		return results
	}
}
func ProjectQueryWithExecutor(executor contracts.SqlExecutor) *table.Table[ProjectModel] {
	return ProjectQuery().SetExecutor(executor)
}

func ProjectQuery() *table.Table[ProjectModel] {
	return table.NewQuery(ProjectDefine.TableName, NewProjectModel).
		SetPrimaryKey("id").
		SetCreatedTimeColumn("created_at").
		SetUpdatedTimeColumn("updated_at").
		SetRelation( // belongsTo: User
			ProjectUserRelation,
			ProjectModelLocalKeyGetter("user_id"),
			ProjectModelRelationGetter(UserQuery, "id"),
			ProjectModelSingleRelationSetter[*UserModel](ProjectUserRelation),
		).
		SetWiths(ProjectDefine.With...)
}

func (model *ProjectModel) Hidden(fields ...string) *ProjectModel {
	for _, field := range fields {
		if model._hidden == nil {
			model._hidden = map[string]struct{}{
				field: struct{}{},
			}
		} else {
			model._hidden[field] = struct{}{}
		}

	}

	return model
}

func (model *ProjectModel) Exists() bool {
	return ProjectQuery().Where("id", model.GetPrimaryKey()).Count() > 0
}

func (model *ProjectModel) Save() contracts.Exception {
	if model._update == nil {
		return nil
	}
	if ProjectDefine.Saving != nil {
		if err := ProjectDefine.Saving(model); err != nil {
			return err
		}
	}
	_, err := ProjectQuery().Where("id", model.GetPrimaryKey()).UpdateE(model._update)
	if err == nil {
		model._update = nil
		if ProjectDefine.Saved != nil {
			ProjectDefine.Saved(model)
		}
	}

	return err
}

func (model *ProjectModel) Set(fields contracts.Fields) {
	for key, value := range fields {

		switch key {
		case "id":
			switch v := value.(type) {
			case uint64:
				model.SetId(v)
			case func() uint64:
				model.SetId(v())
			case string:
				var vd uint64
				err := json.Unmarshal([]byte(v), &vd)
				if err != nil {
					logs.Default().Warn("Failed to Parse field " + key)
					continue
				}
				model.SetId(vd)

			case []byte:
				var vd uint64
				err := json.Unmarshal(v, &vd)
				if err != nil {
					logs.Default().Warn("Failed to Parse field " + key)
					continue
				}
				model.SetId(vd)

			default:
				model.SetId(cast.ToUint64(v))
			}
		case "uuid":
			switch v := value.(type) {
			case string:
				model.SetUuid(v)
			case func() string:
				model.SetUuid(v())
			case []byte:
				model.SetUuid(string(v))

			default:
				model.SetUuid(cast.ToString(v))
			}
		case "name":
			switch v := value.(type) {
			case string:
				model.SetName(v)
			case func() string:
				model.SetName(v())
			case []byte:
				model.SetName(string(v))

			default:
				model.SetName(cast.ToString(v))
			}
		case "creator_id":
			switch v := value.(type) {
			case int32:
				model.SetCreatorId(v)
			case func() int32:
				model.SetCreatorId(v())
			case string:
				var vd int32
				err := json.Unmarshal([]byte(v), &vd)
				if err != nil {
					logs.Default().Warn("Failed to Parse field " + key)
					continue
				}
				model.SetCreatorId(vd)

			case []byte:
				var vd int32
				err := json.Unmarshal(v, &vd)
				if err != nil {
					logs.Default().Warn("Failed to Parse field " + key)
					continue
				}
				model.SetCreatorId(vd)

			default:
				model.SetCreatorId(cast.ToInt32(v))
			}
		case "group_id":
			switch v := value.(type) {
			case int32:
				model.SetGroupId(v)
			case func() int32:
				model.SetGroupId(v())
			case string:
				var vd int32
				err := json.Unmarshal([]byte(v), &vd)
				if err != nil {
					logs.Default().Warn("Failed to Parse field " + key)
					continue
				}
				model.SetGroupId(vd)

			case []byte:
				var vd int32
				err := json.Unmarshal(v, &vd)
				if err != nil {
					logs.Default().Warn("Failed to Parse field " + key)
					continue
				}
				model.SetGroupId(vd)

			default:
				model.SetGroupId(cast.ToInt32(v))
			}
		case "key_id":
			switch v := value.(type) {
			case int32:
				model.SetKeyId(v)
			case func() int32:
				model.SetKeyId(v())
			case string:
				var vd int32
				err := json.Unmarshal([]byte(v), &vd)
				if err != nil {
					logs.Default().Warn("Failed to Parse field " + key)
					continue
				}
				model.SetKeyId(vd)

			case []byte:
				var vd int32
				err := json.Unmarshal(v, &vd)
				if err != nil {
					logs.Default().Warn("Failed to Parse field " + key)
					continue
				}
				model.SetKeyId(vd)

			default:
				model.SetKeyId(cast.ToInt32(v))
			}
		case "repo_address":
			switch v := value.(type) {
			case string:
				model.SetRepoAddress(v)
			case func() string:
				model.SetRepoAddress(v())
			case []byte:
				model.SetRepoAddress(string(v))

			default:
				model.SetRepoAddress(cast.ToString(v))
			}
		case "project_path":
			switch v := value.(type) {
			case string:
				model.SetProjectPath(v)
			case func() string:
				model.SetProjectPath(v())
			case []byte:
				model.SetProjectPath(string(v))

			default:
				model.SetProjectPath(cast.ToString(v))
			}
		case "default_branch":
			switch v := value.(type) {
			case string:
				model.SetDefaultBranch(v)
			case func() string:
				model.SetDefaultBranch(v())
			case []byte:
				model.SetDefaultBranch(string(v))

			default:
				model.SetDefaultBranch(cast.ToString(v))
			}
		case "settings":
			switch v := value.(type) {
			case string:
				model.SetSettings(v)
			case func() string:
				model.SetSettings(v())
			case []byte:
				model.SetSettings(string(v))

			default:
				model.SetSettings(cast.ToString(v))
			}
		case "created_at":
			switch v := value.(type) {
			case string:
				model.SetCreatedAt(v)
			case func() string:
				model.SetCreatedAt(v())
			case []byte:
				model.SetCreatedAt(string(v))

			default:
				model.SetCreatedAt(cast.ToString(v))
			}
		case "updated_at":
			switch v := value.(type) {
			case string:
				model.SetUpdatedAt(v)
			case func() string:
				model.SetUpdatedAt(v())
			case []byte:
				model.SetUpdatedAt(string(v))

			default:
				model.SetUpdatedAt(cast.ToString(v))
			}
		case string(ProjectUserRelation):
			model.SetUser(value.(*UserModel))
		}

	}
}

func (model *ProjectModel) Only(key ...string) contracts.Fields {
	var fields = make(contracts.Fields)
	for _, k := range key {
		if k == "id" {
			fields[k] = model.GetId()
			continue
		}
		if k == "uuid" {
			fields[k] = model.GetUuid()
			continue
		}
		if k == "name" {
			fields[k] = model.GetName()
			continue
		}
		if k == "creator_id" {
			fields[k] = model.GetCreatorId()
			continue
		}
		if k == "group_id" {
			fields[k] = model.GetGroupId()
			continue
		}
		if k == "key_id" {
			fields[k] = model.GetKeyId()
			continue
		}
		if k == "repo_address" {
			fields[k] = model.GetRepoAddress()
			continue
		}
		if k == "project_path" {
			fields[k] = model.GetProjectPath()
			continue
		}
		if k == "default_branch" {
			fields[k] = model.GetDefaultBranch()
			continue
		}
		if k == "settings" {
			fields[k] = model.GetSettings()
			continue
		}
		if k == "created_at" {
			fields[k] = model.GetCreatedAt()
			continue
		}
		if k == "updated_at" {
			fields[k] = model.GetUpdatedAt()
			continue
		}

		if ProjectDefine.Appends[k] != nil {
			fields[k] = ProjectDefine.Appends[k](model)
		}
	}
	return fields
}

func (model *ProjectModel) Get(key string) any {
	switch key {
	case "id":
		return model.GetId()
	case "uuid":
		return model.GetUuid()
	case "name":
		return model.GetName()
	case "creator_id":
		return model.GetCreatorId()
	case "group_id":
		return model.GetGroupId()
	case "key_id":
		return model.GetKeyId()
	case "repo_address":
		return model.GetRepoAddress()
	case "project_path":
		return model.GetProjectPath()
	case "default_branch":
		return model.GetDefaultBranch()
	case "settings":
		return model.GetSettings()
	case "created_at":
		return model.GetCreatedAt()
	case "updated_at":
		return model.GetUpdatedAt()
	}

	if value, exists := model._append[key]; exists {
		return value
	}

	if fn, exists := ProjectDefine.Appends[key]; exists {
		model._append[key] = fn(model)
		return model._append[key]
	}

	switch contracts.RelationType(key) {
	case ProjectUserRelation:
		return model.User()
	}

	return nil
}

func (model *ProjectModel) Except(keys ...string) contracts.Fields {
	var excepts = map[string]struct{}{}
	for _, k := range keys {
		excepts[k] = struct{}{}
	}
	var fields = make(contracts.Fields)
	for key, value := range model.ToFields() {
		if _, ok := excepts[key]; ok {
			continue
		}
		fields[key] = value
	}
	return fields
}

func (model *ProjectModel) ToFields() contracts.Fields {
	if model == nil {
		return nil
	}

	model.Hidden(ProjectDefine.Hidden...)

	fields := contracts.Fields{}
	if _, exists := model._hidden["id"]; !exists {
		fields["id"] = model.GetId()
	}
	if _, exists := model._hidden["uuid"]; !exists {
		fields["uuid"] = model.GetUuid()
	}
	if _, exists := model._hidden["name"]; !exists {
		fields["name"] = model.GetName()
	}
	if _, exists := model._hidden["creator_id"]; !exists {
		fields["creator_id"] = model.GetCreatorId()
	}
	if _, exists := model._hidden["group_id"]; !exists {
		fields["group_id"] = model.GetGroupId()
	}
	if _, exists := model._hidden["key_id"]; !exists {
		fields["key_id"] = model.GetKeyId()
	}
	if _, exists := model._hidden["repo_address"]; !exists {
		fields["repo_address"] = model.GetRepoAddress()
	}
	if _, exists := model._hidden["project_path"]; !exists {
		fields["project_path"] = model.GetProjectPath()
	}
	if _, exists := model._hidden["default_branch"]; !exists {
		fields["default_branch"] = model.GetDefaultBranch()
	}
	if _, exists := model._hidden["settings"]; !exists {
		fields["settings"] = model.GetSettings()
	}
	if _, exists := model._hidden["created_at"]; !exists {
		fields["created_at"] = model.GetCreatedAt()
	}
	if _, exists := model._hidden["updated_at"]; !exists {
		fields["updated_at"] = model.GetUpdatedAt()
	}

	for key := range ProjectDefine.Appends {
		value := model.Get(key)
		if fieldsProvider, ok := value.(contracts.FieldsProvider); ok {
			fields[key] = fieldsProvider.ToFields()
		} else {
			fields[key] = value
		}
	}

	for key := range model._relation_loaded {
		switch key {
		case ProjectUserRelation:
			fields[string(key)] = model._User.ToFields()
		}
	}

	for key, value := range model._raw {
		_, hidden := model._hidden[key]
		if _, exists := fields[key]; !exists && !hidden {
			fields[key] = value
		}
	}

	return fields
}

func (model *ProjectModel) Update(fields contracts.Fields) contracts.Exception {

	if ProjectDefine.Updating != nil {
		if err := ProjectDefine.Updating(model, fields); err != nil {
			return err
		}
	}

	if model._update != nil {
		utils.MergeFields(model._update, fields)
	}

	_, err := ProjectQuery().Where("id", model.GetPrimaryKey()).UpdateE(fields)

	if err == nil {
		model.Set(fields)
		model._update = nil
		if ProjectDefine.Updated != nil {
			ProjectDefine.Updated(model, fields)
		}
	}

	return err
}

func (model *ProjectModel) Refresh() contracts.Exception {
	fields, err := table.ArrayQuery("projects").Where("id", model.GetPrimaryKey()).FirstE()
	if err != nil {
		return err
	}

	model.Set(*fields)
	return nil
}

func (model *ProjectModel) Delete() contracts.Exception {

	if ProjectDefine.Deleting != nil {
		if err := ProjectDefine.Deleting(model); err != nil {
			return err
		}
	}

	_, err := ProjectQuery().Where("id", model.GetPrimaryKey()).DeleteE()
	if err == nil && ProjectDefine.Deleted != nil {
		ProjectDefine.Deleted(model)
	}

	return err
}

func (model *ProjectModel) GetPrimaryKey() any {
	if ProjectDefine.PrimaryKeyGetter != nil {
		return ProjectDefine.PrimaryKeyGetter(model)
	}

	return model.Id
}

func (model *ProjectModel) GetId() uint64 {
	if ProjectDefine.IdGetter != nil {
		return ProjectDefine.IdGetter(model, model.Id)
	}
	return model.Id
}

func (model *ProjectModel) SetId(value uint64) {
	if ProjectDefine.IdSetter != nil {
		value = ProjectDefine.IdSetter(model, value)
	}

	if model._update == nil {
		model._update = contracts.Fields{"id": value}
	} else {
		model._update["id"] = value
	}
	model.Id = value
}

func (model *ProjectModel) GetUuid() string {
	if ProjectDefine.UuidGetter != nil {
		return ProjectDefine.UuidGetter(model, model.Uuid)
	}
	return model.Uuid
}

func (model *ProjectModel) SetUuid(value string) {
	if ProjectDefine.UuidSetter != nil {
		value = ProjectDefine.UuidSetter(model, value)
	}

	if model._update == nil {
		model._update = contracts.Fields{"uuid": value}
	} else {
		model._update["uuid"] = value
	}
	model.Uuid = value
}

func (model *ProjectModel) GetName() string {
	if ProjectDefine.NameGetter != nil {
		return ProjectDefine.NameGetter(model, model.Name)
	}
	return model.Name
}

func (model *ProjectModel) SetName(value string) {
	if ProjectDefine.NameSetter != nil {
		value = ProjectDefine.NameSetter(model, value)
	}

	if model._update == nil {
		model._update = contracts.Fields{"name": value}
	} else {
		model._update["name"] = value
	}
	model.Name = value
}

func (model *ProjectModel) GetCreatorId() int32 {
	if ProjectDefine.CreatorIdGetter != nil {
		return ProjectDefine.CreatorIdGetter(model, model.CreatorId)
	}
	return model.CreatorId
}

func (model *ProjectModel) SetCreatorId(value int32) {
	if ProjectDefine.CreatorIdSetter != nil {
		value = ProjectDefine.CreatorIdSetter(model, value)
	}

	if model._update == nil {
		model._update = contracts.Fields{"creator_id": value}
	} else {
		model._update["creator_id"] = value
	}
	model.CreatorId = value
}

func (model *ProjectModel) GetGroupId() int32 {
	if ProjectDefine.GroupIdGetter != nil {
		return ProjectDefine.GroupIdGetter(model, model.GroupId)
	}
	return model.GroupId
}

func (model *ProjectModel) SetGroupId(value int32) {
	if ProjectDefine.GroupIdSetter != nil {
		value = ProjectDefine.GroupIdSetter(model, value)
	}

	if model._update == nil {
		model._update = contracts.Fields{"group_id": value}
	} else {
		model._update["group_id"] = value
	}
	model.GroupId = value
}

func (model *ProjectModel) GetKeyId() int32 {
	if ProjectDefine.KeyIdGetter != nil {
		return ProjectDefine.KeyIdGetter(model, model.KeyId)
	}
	return model.KeyId
}

func (model *ProjectModel) SetKeyId(value int32) {
	if ProjectDefine.KeyIdSetter != nil {
		value = ProjectDefine.KeyIdSetter(model, value)
	}

	if model._update == nil {
		model._update = contracts.Fields{"key_id": value}
	} else {
		model._update["key_id"] = value
	}
	model.KeyId = value
}

func (model *ProjectModel) GetRepoAddress() string {
	if ProjectDefine.RepoAddressGetter != nil {
		return ProjectDefine.RepoAddressGetter(model, model.RepoAddress)
	}
	return model.RepoAddress
}

func (model *ProjectModel) SetRepoAddress(value string) {
	if ProjectDefine.RepoAddressSetter != nil {
		value = ProjectDefine.RepoAddressSetter(model, value)
	}

	if model._update == nil {
		model._update = contracts.Fields{"repo_address": value}
	} else {
		model._update["repo_address"] = value
	}
	model.RepoAddress = value
}

func (model *ProjectModel) GetProjectPath() string {
	if ProjectDefine.ProjectPathGetter != nil {
		return ProjectDefine.ProjectPathGetter(model, model.ProjectPath)
	}
	return model.ProjectPath
}

func (model *ProjectModel) SetProjectPath(value string) {
	if ProjectDefine.ProjectPathSetter != nil {
		value = ProjectDefine.ProjectPathSetter(model, value)
	}

	if model._update == nil {
		model._update = contracts.Fields{"project_path": value}
	} else {
		model._update["project_path"] = value
	}
	model.ProjectPath = value
}

func (model *ProjectModel) GetDefaultBranch() string {
	if ProjectDefine.DefaultBranchGetter != nil {
		return ProjectDefine.DefaultBranchGetter(model, model.DefaultBranch)
	}
	return model.DefaultBranch
}

func (model *ProjectModel) SetDefaultBranch(value string) {
	if ProjectDefine.DefaultBranchSetter != nil {
		value = ProjectDefine.DefaultBranchSetter(model, value)
	}

	if model._update == nil {
		model._update = contracts.Fields{"default_branch": value}
	} else {
		model._update["default_branch"] = value
	}
	model.DefaultBranch = value
}

func (model *ProjectModel) GetSettings() string {
	if ProjectDefine.SettingsGetter != nil {
		return ProjectDefine.SettingsGetter(model, model.Settings)
	}
	return model.Settings
}

func (model *ProjectModel) SetSettings(value string) {
	if ProjectDefine.SettingsSetter != nil {
		value = ProjectDefine.SettingsSetter(model, value)
	}

	if model._update == nil {
		model._update = contracts.Fields{"settings": value}
	} else {
		model._update["settings"] = value
	}
	model.Settings = value
}

func (model *ProjectModel) GetCreatedAt() string {
	if ProjectDefine.CreatedAtGetter != nil {
		return ProjectDefine.CreatedAtGetter(model, model.CreatedAt)
	}
	return model.CreatedAt
}

func (model *ProjectModel) SetCreatedAt(value string) {
	if ProjectDefine.CreatedAtSetter != nil {
		value = ProjectDefine.CreatedAtSetter(model, value)
	}

	if model._update == nil {
		model._update = contracts.Fields{"created_at": value}
	} else {
		model._update["created_at"] = value
	}
	model.CreatedAt = value
}

func (model *ProjectModel) GetUpdatedAt() string {
	if ProjectDefine.UpdatedAtGetter != nil {
		return ProjectDefine.UpdatedAtGetter(model, model.UpdatedAt)
	}
	return model.UpdatedAt
}

func (model *ProjectModel) SetUpdatedAt(value string) {
	if ProjectDefine.UpdatedAtSetter != nil {
		value = ProjectDefine.UpdatedAtSetter(model, value)
	}

	if model._update == nil {
		model._update = contracts.Fields{"updated_at": value}
	} else {
		model._update["updated_at"] = value
	}
	model.UpdatedAt = value
}

// UserQuery @belongsTo
func (model *ProjectModel) User() *UserModel {
	_, exists := model._relation_loaded[ProjectUserRelation]
	if !exists {
		value := model.UserQuery().First()
		model.SetUser(value)
		return value
	}
	return model._User
}

// UserQuery @belongsTo
func (model *ProjectModel) UserQuery() contracts.QueryBuilder[UserModel] {
	return UserQuery().Where("id", model.Get("user_id"))
}

// UserQuery @belongsTo
func (model *ProjectModel) SetUser(value *UserModel) {
	if model._relation_loaded == nil {
		model._relation_loaded = make(map[contracts.RelationType]struct{})
	}
	model._relation_loaded[ProjectUserRelation] = struct{}{}
	model._User = value
}
