// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.24.0
//
// updated_at: 2025-03-24 20:22:07
// source: pro/Project.proto
// 
package project

import (
	"github.com/goal-web/contracts"
)

type CreateProjectReq struct {
	Uuid          string `json:"uuid" query:"uuid" form:"uuid"`
	Name          string `json:"name" query:"name" form:"name"`
	CreatorId     int64  `json:"creator_id" query:"creator_id" form:"creator_id"`
	GroupId       int64  `json:"group_id" query:"group_id" form:"group_id"`
	KeyId         int64  `json:"key_id" query:"key_id" form:"key_id"`
	RepoAddress   string `json:"repo_address" query:"repo_address" form:"repo_address"`
	ProjectPath   string `json:"project_path" query:"project_path" form:"project_path"`
	DefaultBranch string `json:"default_branch" query:"default_branch" form:"default_branch"`
	Settings      string `json:"settings" query:"settings" form:"settings"`
}

func (model *CreateProjectReq) ToFields() contracts.Fields {
	if model == nil {
		return nil
	}
	fields := contracts.Fields{
		"uuid":           model.Uuid,
		"name":           model.Name,
		"creator_id":     model.CreatorId,
		"group_id":       model.GroupId,
		"key_id":         model.KeyId,
		"repo_address":   model.RepoAddress,
		"project_path":   model.ProjectPath,
		"default_branch": model.DefaultBranch,
		"settings":       model.Settings,
	}
	return fields
}
