// Code generated by goal-cli. DO NOT EDIT.
// versions:
// 	goal-cli v0.5.24
// 	go       go1.24.0
//
// updated_at: 2025-03-24 20:22:07
// source: pro/Project.proto
// 
package project

import (
	"github.com/goal-web/contracts"
)

type ListProjectsReq struct {
	Page    int64 `json:"page" query:"page" form:"page"`
	PerPage int64 `json:"per_page" query:"per_page" form:"per_page"`
}

func (model *ListProjectsReq) ToFields() contracts.Fields {
	if model == nil {
		return nil
	}
	fields := contracts.Fields{
		"page":     model.Page,
		"per_page": model.PerPage,
	}
	return fields
}
